apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: flask-vs
spec:
  hosts:
  - "*"
  gateways:
  - flask-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: flask-app
        port:
          number: 80 